version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
    env_file:
      - ./backend/.env
    networks:
      - fileshare-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000
      - NESTJS_BACKEND_URL=http://backend:8000
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - fileshare-network
    restart: unless-stopped

networks:
  fileshare-network:
    driver: bridge